### ISSUE TITLE
How does it compare to Firefox Containers feature?

### ISSUE THREAD

**Issue by tsilvs** [Mimieam/workSpaceLive#7]
It is certainly missing from Chrome, and your extension feels like it could do such a thing. Does it, or it is just a UX/UI thing?

**Comment by Mimieam** [comment]
Sorry for the very late reply, I never got the notification for this. 
Funny enough I didn't know this was a thing, but yes it's pretty much the same as Firefox containers + a tab manager for your currently opened tabs on top.
